# Alembic Configuration File
# This file does not need much human editing,
# though it does contain some customizations over what you might
# get with the standard "alembic init" wizard.
# All settings can also be passed to the `alembic` programmatic API, which
# avoids having to write/read this file in many cases.

# path to migration files
script_location = agent_service/migrations

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
#file_template = %%(created_at)s_%%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepend_sys_path = .

# timezone to use when rendering the date
# within the migration file as well as the filename.
# string value is passed to the constructor of datetime.datetime for the "timezone" argument
# Leave blank for localtime
# timezone =

# max length of characters to apply to the
# "slug" field that's auto-generated by the revision file
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# If false, revision files are not sourced from setuptools entry points
# loaded entry points are instead loaded from pkg_resources by default.
# loaded entry points from setuptools are also scanned, loaded, then
# compared to those loaded from pkg_resources by default. When this flag
# is true, then setuptools entry points will not be scanned load from
# pkg_resources.
# loaded_entry_points = false

# ===========================================================================
# Logging configuration
# ===========================================================================
# via Flask-Migrate, unless otherwise augmented such that it is to
# be given its own logger configuration.

[loggers]
keys = root,sqlalchemy.engine

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy.engine]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
