site_name: Master of Puppets
site_url: https://dev.master-of-puppets.work/docs/
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: indigo
plugins:
  - search
  - privacy
  - offline
  - swagger-ui-tag

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - tables

nav:
  - Home: index.md
  - Developer:
    - Architecture: developer/architecture.md
  - API Reference:
    - Overview: api-reference/index.md
